import { describe, it, expect, vi, beforeEach } from "vitest";

/**
 * Actions belong to a step of the path.
 *
 * Two properties carry this slice, and both are asserted here against the real
 * generation path rather than against a helper:
 *
 *  1. A step key the model invented, or one that names a step this person is
 *     not on, is dropped to NO step. It is never persisted, because a stored
 *     key nothing answers to would put the action under a heading that does not
 *     exist. The action itself is kept either way.
 *  2. The reference is the path's own candidate key, not a step ROW. A path is
 *     regenerated by superseding its steps and inserting a fresh set, so a row
 *     id would come loose on every rebuild and take every action's place in the
 *     plan with it. The regeneration test below is the one that proves it.
 */

// ── The model, and everything the engine reaches for around it ───────────────

const llmGenerateText = vi.fn();
vi.mock("../llm.js", () => ({
  llmGenerateText: (...args: unknown[]) => llmGenerateText(...args),
}));
vi.mock("../../agent/index.js", () => ({
  getModel: () => ({}) as never,
  getModelSlug: () => "anthropic/claude-sonnet-4.5",
}));
vi.mock("../activity.js", () => ({ logLlmUsage: vi.fn(), actualLlmCostUsd: () => undefined }));
vi.mock("../billing.js", () => ({ isTenantDisabled: async () => false }));
vi.mock("../pii-scrubber.js", () => ({
  buildAliasMap: async () => ({ forward: new Map(), reverse: new Map() }),
  scrub: (x: unknown) => x,
  descrub: (x: unknown) => x,
  descrubObject: (x: unknown) => x,
}));
vi.mock("../account-balances.js", () => ({
  excludedTxnAccountIds: async () => [] as string[],
  fetchAccountsWithBalances: async () => [] as unknown[],
}));
vi.mock("../goal-progress.js", () => ({
  buildGoalAccountMap: () => new Map(),
  resolveGoalAmount: () => ({ amount: 0 }),
}));
vi.mock("../profile-resolver.js", () => ({
  readHouseholdProfile: async () => null,
  readOwnerPersonalProfile: async () => null,
  resolveProfile: () => ({
    annualIncome: null,
    filingStatus: null,
    stateOfResidence: null,
    riskTolerance: null,
    retirementAge: null,
    employerMatchPercent: null,
    age: null,
  }),
}));

/** The path this tenant is standing on, set per test. */
let pathSteps: Array<{ key: string; step: number; title: string }> = [];
vi.mock("../path-generator.js", () => ({
  readPathSteps: async () => pathSteps,
}));

// ── A database that answers, without being one ──────────────────────────────
//
// Every read the engine makes is a drizzle chain ending in an array, and all of
// them tolerate an empty one. The single exception is the accounts read, which
// decides whether there is a household to analyse at all, so that is the only
// table this stands anything up for.

const inserted: Record<string, unknown>[] = [];

function rowsFor(table: unknown): unknown[] {
  return table === accounts
    ? [
        {
          name: "Everyday checking",
          type: "depository",
          subtype: "checking",
          metadata: null,
          accountId: "00000000-0000-4000-8000-000000000001",
          excludeFromNetWorth: false,
          invertBalance: false,
        },
      ]
    : [];
}

function selectChain() {
  let table: unknown = null;
  const self: Record<string, unknown> = {
    from: (t: unknown) => {
      table = t;
      return self;
    },
    innerJoin: () => self,
    leftJoin: () => self,
    where: () => self,
    orderBy: () => self,
    groupBy: () => self,
    limit: () => self,
    then: (res: (v: unknown) => unknown, rej: (e: unknown) => unknown) =>
      Promise.resolve(rowsFor(table)).then(res, rej),
  };
  return self;
}

function settled() {
  const self: Record<string, unknown> = {
    where: () => self,
    onConflictDoUpdate: () => self,
    returning: () => Promise.resolve([]),
    then: (res: (v: unknown) => unknown, rej: (e: unknown) => unknown) =>
      Promise.resolve([]).then(res, rej),
  };
  return self;
}

vi.mock("../db.js", () => ({
  db: {
    select: () => selectChain(),
    query: { goalAccounts: { findMany: async () => [] } },
    delete: () => settled(),
    insert: (table: unknown) => ({
      values: (row: Record<string, unknown>) => {
        // Only the actions themselves; the profile bookkeeping row is noise.
        if ("pathStepKey" in row) inserted.push(row);
        void table;
        return settled();
      },
    }),
  },
}));

import { accounts } from "@lasagna/core";
import { generateInsights } from "../insights-engine.js";

/** What the model hands back, before anything is validated. */
function modelReturns(items: Array<Record<string, unknown>>) {
  llmGenerateText.mockResolvedValue({
    text: JSON.stringify(items),
    usage: { inputTokens: 900, outputTokens: 400 },
  });
}

function action(title: string, pathStepKey?: string) {
  return {
    category: "debt",
    urgency: "high",
    type: "debt",
    title,
    description: "Because the numbers say so.",
    impact: "Save $340/yr",
    impactColor: "green",
    chatPrompt: "Tell me more",
    ...(pathStepKey === undefined ? {} : { pathStepKey }),
  };
}

const TENANT = "00000000-0000-4000-8000-0000000000aa";

beforeEach(() => {
  inserted.length = 0;
  llmGenerateText.mockReset();
  pathSteps = [
    { key: "stabilize", step: 1, title: "Save a starter emergency fund" },
    { key: "debt:11111111-1111-4111-8111-111111111111", step: 2, title: "Pay off a card" },
    { key: "emergency-fund", step: 3, title: "Save a full emergency fund" },
  ];
});

describe("attaching an action to the step it serves", () => {
  it("stores the key when the step is on the path", async () => {
    modelReturns([action("Pay down your card", "debt:11111111-1111-4111-8111-111111111111")]);

    expect(await generateInsights(TENANT)).toBe(1);
    expect(inserted[0].pathStepKey).toBe("debt:11111111-1111-4111-8111-111111111111");
  });

  it("lands an action with no step, and still shows it", async () => {
    modelReturns([action("Dispute the charge you did not make", "none")]);

    expect(await generateInsights(TENANT)).toBe(1);
    expect(inserted).toHaveLength(1);
    expect(inserted[0].pathStepKey).toBeNull();
  });

  it("drops a key that is not on the path rather than persisting it", async () => {
    modelReturns([
      // A key this person's path does not carry. It reads like one, which is
      // exactly why it cannot be trusted: nothing downstream would ever find a
      // step behind it, and the action would sit under a heading that is not
      // there.
      action("Pay off the yacht", "debt:99999999-9999-4999-8999-999999999999"),
      // A step that was taken off the path, so `readPathSteps` does not carry
      // it. Same answer.
      action("Write your will", "will-trust"),
      // A key the model adapted rather than echoed.
      action("Top up the buffer", "Stabilize"),
    ]);

    expect(await generateInsights(TENANT)).toBe(3);
    expect(inserted.map((r) => r.pathStepKey)).toEqual([null, null, null]);
    // Every one of them is still an action the person reads.
    expect(inserted.map((r) => r.title)).toEqual([
      "Pay off the yacht",
      "Write your will",
      "Top up the buffer",
    ]);
  });

  it("attaches nothing when the person has no path", async () => {
    pathSteps = [];
    modelReturns([action("Pay down your card", "stabilize")]);

    expect(await generateInsights(TENANT)).toBe(1);
    expect(inserted[0].pathStepKey).toBeNull();
  });

  it("shows the model the steps it is allowed to name", async () => {
    modelReturns([action("Pay down your card", "stabilize")]);
    await generateInsights(TENANT);

    const prompt = String(llmGenerateText.mock.calls[0][1].prompt);
    expect(prompt).toContain("financial path");
    expect(prompt).toContain('"key":"stabilize"');
    expect(prompt).toContain('"step":2');
    expect(prompt).toContain("Save a full emergency fund");
  });
});
